// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcmzsajtixyhqmbpqwso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbXpzYWp0aXh5aHFtYnBxd3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzM0NzYsImV4cCI6MjA3MjMwOTQ3Nn0.QGN6g8oDr5lHpTLI9HQ5FZ37uLsTNu-klo2GO-w1P04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});